# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/node:9.11.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    
      - checkout

      - run: |
          curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

      - run: |
          nvm install v10
          node -v
          nvm alias default v10
      - run: |
          node -v

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}

      - run: 
          name: install-apollo
          command: npm install -g apollo@2.4.4	  

      - save_cache: # special step to save the dependency cache
         key: dependency-cache-{{ checksum "package.json" }}
         paths:
           - ./node_modules

      - run: |
          curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
          
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV

      - run: |
          nvm install v10
          nvm alias default v10
          node -v
      - run: |
          npm -v

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            
      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
          
       - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}

      - run: 
          name: install-apollo
          command: npm i -g apollo	  

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # run tests!
      - run: cat /dev/null | sbt test:test
      - run: sbt ";set scalaJSStage in Global := FullOptStage; tests/test"
